### ISSUE TITLE
about data augmentation and training CoIN on lbl/ulb samples

### ISSUE THREAD

**Issue by adv010** [xmuqimingxia/CoIn#4]
Hi Team,

I have some question on how semi-supervised data is being prepared and loaded in CoIN.   I've used 3dioumatch as a base reference against the same.

1. Below is a snippet to load labeled split and unlabeled from 3dioumatch.

https://github.com/yezhen17/3DIoUMatch-PVRCNN/blob/289eeacc24e7d793203f6cf2e696805bc83b8893/pcdet/datasets/kitti/kitti_dataset_ssl.py#L45-L63

Could you confirm whether the same approach is used to load labeled/unlabeled samples for CoIN / CoIN++ ? 

2. 

Below is the data augmentor section from 3dioumatch with augments and sample_groups for db_sampling

`DATA_CONFIG:
    _BASE_CONFIG_: cfgs/dataset_configs/kitti_dataset_ssl.yaml
    DATA_AUGMENTOR:
        DISABLE_AUG_LIST: ['placeholder']
        AUG_CONFIG_LIST:
            - NAME: gt_sampling
              USE_ROAD_PLANE: True
              DB_INFO_PATH:
                  - kitti_dbinfos_train.pkl
              PREPARE: {
                 filter_by_min_points: ['Car:5', 'Pedestrian:5', 'Cyclist:5'],
                 filter_by_difficulty: [-1],
              }

              SAMPLE_GROUPS: ['Car:15','Pedestrian:10', 'Cyclist:10']
              NUM_POINT_FEATURES: 4
              DATABASE_WITH_FAKELIDAR: False
              REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
              LIMIT_WHOLE_SCENE: True

            - NAME: random_world_flip
              ALONG_AXIS_LIST: ['x']

            - NAME: random_world_rotation
              WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]

            - NAME: random_world_scaling
              WORLD_SCALE_RANGE: [0.95, 1.05]
`

What's the data augmentor section for CoIN / CoIN++?

**Comment by xmuqimingxia** [comment]
I will upload a train.pkl file to the online drive in a week.

**Comment by xmuqimingxia** [comment]
We provide a kitti_ Info_train.pkl file is convenient for running code.  We have not made any modifications to the code in the GTsampling section, which is consistent with the baseline method. 

kitti_ Info_train.pkl ： https://drive.google.com/file/d/1342-YP-w8xbC2PDGcaoSASaJkjHKN89u/view?usp=sharing

**Comment by adv010** [comment]
Thanks for the pkl, and the clarification for GT Sampling!

Could you confirm whether the configurations for random_world_flip, random_world_rotation and random_world scaling given in this question are used as same in CoIN/ CoIN++?

**Comment by xmuqimingxia** [comment]
our configurations:
DATA_AUGMENTOR:
    DISABLE_AUG_LIST: ['placeholder']
    AUG_CONFIG_LIST:
        - NAME: gt_sampling
          USE_ROAD_PLANE: True
          DB_INFO_PATH:
              - kitti_dbinfos_train.pkl
          PREPARE: {
             filter_by_min_points: ['Car:5', 'Pedestrian:5', 'Cyclist:5'],
             filter_by_difficulty: [-1],
          }

          SAMPLE_GROUPS: ['Car:20','Pedestrian:15', 'Cyclist:15']
          NUM_POINT_FEATURES: 4
          DATABASE_WITH_FAKELIDAR: False
          REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
          LIMIT_WHOLE_SCENE: True

        - NAME: random_world_flip
          ALONG_AXIS_LIST: ['x']

        - NAME: random_world_rotation
          WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]

        - NAME: random_world_scaling
          WORLD_SCALE_RANGE: [0.95, 1.05]
