### ISSUE TITLE
How to understand the MCcont loss?

### ISSUE THREAD

**Issue by whuhxb** [xmuqimingxia/CoIn#6]
Dear author @xmuqimingxia @im-djh 

Thanks for the wonderful work.

I have one question. How to understand MCcont loss in this work CoIn? Have you ever tested MCcont loss on the full supervised scenarios? How is the performance? Or, the MCcont loss could be suitable for common full supervision scenes? Thanks a lot.

Xiaobing Han

**Comment by xmuqimingxia** [comment]
![image](https://github.com/xmuqimingxia/CoIn/assets/108978798/0612711e-055d-425a-8ab0-eae55efaddb7)

We have tested the MCcont under full supervision in CenterPoint (KITTI dataset), and the experimental results are shown in the figure above. We haven't conducted too much testing on other algorithms.

MCcont loss is proposed to increase the feature discrimination ability of the backbone network.
